### PR TITLE
Use f12 for go to definition, not f3.

### PR DESCRIPTION
**Pull request by webuniverseio**
Instead of redefining default search key (f3), lets redefine default go to definition key (f12) and only in javascript

### CODE REVIEW

**Comment by makc** [comment]
Up to @potapenko

**Comment by webuniverseio** [comment]
@potapenko Please accept my pull request. Right now you're overriding default behavior for f3 button which is used for search next. That makes search in sublime unusable (well at least uncomfortable). Also you make it for every syntax not only for javascript. I suggest to override default sublime go to definition (f12) button and only in javascript - that seems to be much cleaner solution.

**Comment by webuniverseio** [comment]
@makc do you know if potapenko is around? I'm sure many sublime text users will benifit from remapping of f3 to f12.

**Comment by makc** [comment]
his take is that users should be able to override keymap by editing prefrences file, so he wants to change the way COLT plugin exposes its preferences instead.

**Pull request closed without merging**
